before_install:
- sudo apt-get update
- sudo apt-get install texlive-latex-extra
script:
- pdflatex ./main.tex
deploy:
  provider: releases
  api_key:
    secure: WTVQ/sBB7xU6un5UKKaR5FUWMFoHnurzVqQ6sTSdDa0oxX3n9WTgEYV6VxKWX68Rqgw4H04WUN6ioynW7HCqRHv/OR87rg5KZDFBtGEulrSuCzpO0De0ghSLJq7P3uMBWnuGXMUIXEtFoemXME+WNlDGbzyHynOM4SIa5IbYQaNwwpidnD7+9RIRnVqL38XNS/jqEC4zVSSZSi680RRW364Kga1VUQXFljX09W+qUVNl7xt+RKZW8f3/PvE2qe7K6alMPr74ksgz2ygEe82QOluGUfDO8Zz9M78N+NSztnV8DHl7ZG4l3lG6kKnS+hihx5nio4/iWN+N7ED5EWQyolHQYeIGMge8eIl+94tBMnpTIU+vx0fSdEYMPu/IPgkd2uSmVdQLXKr3O65JMVbphsV1dDa4rSxrUrSFjclrM3fvCXfk0rloTDTft1INC5OtGbsQpGMKIhREHqNAf4ncMkaYp4/LoduWC44Jy4Kt2tSummB0znMNnMZEUtumPD65IobrnuiwHA8lUuyTDo6Btekqj27873/xpjHm6DTRUYzKpqZTJxzXwYY2SN6Zcs+3G7wWv0p/jg+olsef0DrI1S06N6AfeaXiOSN9ANhvx0/MwOGZrdqiJyd8T8R1GgOKYrgF9JboL66qoavkkRXWf+SsdxQ+QYs0Q7JMMkNOvPE=
  file: main.pdf
  skip_cleanup: true
  on:
    repo: ay27/cv
